package fr.olympa.api.redis;

public enum RedisChannel {

	BUNGEE_ASK_SEND_OLYMPAPLAYER,
	BUNGEE_SEND_OLYMPAPLAYER,
	BUNGEE_ASK_SEND_SERVERNAME,
	BUNGEE_SEND_SERVERSINFOS,

	SPIGOT_RECEIVE_ERROR,
	SPIGOT_ASK_SERVERNAME,
	SPIGOT_SEND_OLYMPAPLAYER,
	SPIGOT_SEND_OLYMPAPLAYER_TO_BUNGEE,
	//	SPIGOT_PLAYER_HAS_GROUP_CHANGED,
	SPIGOT_SERVER_CHANGE_STATUS,
	SPIGOT_PLAYER_SWITCH_SERVER,

	SPIGOT_CHANGE_GROUP,
	SPIGOT_CHANGE_GROUP_RECEIVE,
	SPIGOT_ASK_PLAYERSERVER,
	BUNGEE_SEND_PLAYERSERVER,
	//	SPIGOT_RECEIVE_OLYMPAPLAYER,

	SPIGOT_LOBBY_MINIGAME_SCORE,
	SPIGOT_REPORT_SEND,
	;
}
