package fr.olympa.api.redis;

public enum RedisChannel {

	BUNGEE_ASK_SEND_OLYMPAPLAYER,
	BUNGEE_SEND_OLYMPAPLAYER,
	BUNGEE_ASK_SEND_SERVERNAME,
	BUNGEE_SEND_SERVERSINFOS,
	BUNGEE_SEND_SERVERSINFOS2,

	SPIGOT_RECEIVE_ERROR,
	SPIGOT_ASK_SERVERNAME,
	SPIGOT_SEND_OLYMPAPLAYER,
	SPIGOT_SEND_OLYMPAPLAYER_TO_BUNGEE,
	//	SPIGOT_PLAYER_HAS_GROUP_CHANGED,
	SPIGOT_SERVER_CHANGE_STATUS,
	SPIGOT_PLAYER_SWITCH_SERVER,
	SPIGOT_PLAYER_SWITCH_SERVER2,

	SPIGOT_CHANGE_GROUP,
	SPIGOT_CHANGE_GROUP_RECEIVE,
	SPIGOT_ASK_PLAYERSERVER,
	SPIGOT_ASK_SERVERINFO,
	BUNGEE_SEND_PLAYERSERVER,
	//	SPIGOT_RECEIVE_OLYMPAPLAYER,

	SPIGOT_LOBBY_MINIGAME_SCORE,
	SPIGOT_REPORT_SEND,

	SITE_GROUP_CHANGE,
	SPIGOT_COMMAND,
	BUNGEE_COMMAND,
	BUNGEE_SEND_TEAMSPEAKID,
	SPIGOT_SEND_SANCTION,
	BUNGEE_ASK_SOMETHING,
	;
}
