# Utilisatable sur tous les plugins qui extends OlympaPlugin
database:
   default:
      host: localhost
      port: 3306
      user: 'root'
      password: ''

mongo:
   host: 'host'
   port: 4242
   user: 'user'
   password: 'password'