name: OlympaAPI
website: https://olympa.fr
main: fr.olympa.core.spigot.OlympaCore
author: Tristiisch, SkytAsul
version: ${project.fullVersion}
softdepend: [ProtocolSupport, ViaVersion]
api-version: 1.16