name: OlympaAPI
website: https://olympa.fr
main: fr.olympa.core.spigot.OlympaCore
authors: [Tristiisch, SkytAsul]
contributors: [Bullobily]
version: @plugin_version@
softdepend: [ProtocolSupport, ViaVersion]
api-version: 1.16